FROM postgres:${PG_VERSION}-alpine

ENV LANG=C.UTF-8 PGDATA=/pg/data
RUN apk --no-cache add python3 gcc make musl-dev ${CC}

RUN if ${CHECK_CODE} -eq "true" && ${CC} -eq "gcc"; then \
	echo 'http://dl-cdn.alpinelinux.org/alpine/v3.6/main' > /etc/apk/repositories && \
	echo 'http://dl-cdn.alpinelinux.org/alpine/v3.6/community' >> /etc/apk/repositories && \
	apk --no-cache add cppcheck; \
	fi && \
	pip3 install testgres && \
	mkdir -p /pg/data && \
	mkdir /pg/pg_pathman && \
	chown postgres:postgres ${PGDATA} && \
	chmod a+rwx /usr/local/lib/postgresql && \
	chmod a+rwx /usr/local/share/postgresql/extension

ADD . /pg/pg_pathman
WORKDIR /pg/pg_pathman
RUN chmod -R go+rwX /pg/pg_pathman
USER postgres
ENTRYPOINT PGDATA=${PGDATA} CC=${CC} CHECK_CODE=${CHECK_CODE} bash run_tests.sh
